# This github workflow will build the docker image and push it to the container registry
name: DEV CI & CD
run-name: ${{ github.actor }} is running DEV CI & CD
on:
  push:
    branches:
      - dev
      - feature/*
  pull_request:
    branches:
      - dev
      - feature/*

env:
  REGION: singapore
  ENVIRONMENT: dev
  APPLICATION_NAME: map-singapore-app
  DOCKERFILE_PATH: dockerimages
  GITOPS_REPO: Tsuweiquan/my-argocd-poc-gitops

jobs:
  # Run test on PR and on Merge to dev and main branch
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Environment and run Unit Test
        run: |
          echo "Running tests for ${{ env.APPLICATION_NAME }}"
          echo "Unit Test Complete"

      - name: Run Integration Test
        run: |
          echo "Running Integration tests for ${{ env.APPLICATION_NAME }}"
          echo "Integration Test Complete"

  docker-build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-digest: ${{ steps.build-and-push.outputs.digest }}
      image-id: ${{ steps.build-and-push.outputs.imageid }}
      tag-version: ${{ steps.generate-tag-version.outputs.tag-version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Image Tag Version
        id: generate-tag-version
        run: |
          VERSION_TXT_FILEPATH="${{ env.DOCKERFILE_PATH }}/${{ env.APPLICATION_NAME }}/version.txt"
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]] || [[ "${{ github.ref }}" == "refs/heads/feature/*" ]]; then
            TAG_VERSION="SNAPSHOT-$(cat $VERSION_TXT_FILEPATH)"
          else
            TAG_VERSION="$(cat $VERSION_TXT_FILEPATH)"
          fi
          echo $TAG_VERSION
          echo "TAG_VERSION=$TAG_VERSION" >> "$GITHUB_ENV"
          echo "tag-version=$TAG_VERSION" >> "$GITHUB_OUTPUT"

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.DOCKERFILE_PATH }}/${{ env.APPLICATION_NAME }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.APPLICATION_NAME }}:${{ env.TAG_VERSION }}
          platforms: linux/amd64,linux/arm64

  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - tests
      - docker-build-and-push

    steps:
      - env:
          image-digest: ${{ needs.docker-build-and-push.outputs.image-digest }}
          image-id: ${{ needs.docker-build-and-push.outputs.image-id }}
          tag-version: ${{ needs.docker-build-and-push.outputs.tag-version }}
        run: |
          echo "image-digest=${{ env.image-digest }}" >> $GITHUB_ENV
          echo "image-id=${{ env.image-id }}" >> $GITHUB_ENV
          echo "tag-version=${{ env.tag-version }}" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          repository: Tsuweiquan/my-argocd-poc-gitops
          ref: "main"
          token: ${{ secrets.PAT_TOKEN }}
          show-progress: true
          fetch-depth: 0

      - name: Update Tag Version in YAML & Push
        uses: fjogeleit/yaml-update-action@v0.16.1
        with:
          method: Update
          valueFile: "clusters/${{ env.REGION }}/${{ env.ENVIRONMENT }}/${{ env.APPLICATION_NAME }}/values.yaml"
          propertyPath: "image.tag"
          value: ${{ env.tag-version }}
          commitChange: true
          targetBranch: "main"
          # commitMessage: "Update tag version in YAML for ${{ env.APPLICATION_NAME }} to ${{ env.tag-version }} - Commit Hash: ${{ github.sha }}"
          # commitUser: "github-actions[Deployment Bot]"
          commitUserEmail: "github-actions[Deployment Bot]@users.noreply.github.com"
          token: ${{ secrets.PAT_TOKEN }}

      # - name: Push changes
      #   id: push-changes-to-gitops-repo
      #   run: |
      #     git remote set-url origin https://github-actions:${{ secrets.PAT_TOKEN }}@github.com/${{ env.GITOPS_REPO }}.git
      #     git config --global user.email "github-actions[Deployment Bot]@users.noreply.github.com"
      #     git config --global user.name "github-actions[Deployment Bot]"
      #     git status
      #     if git diff --quiet HEAD~1..HEAD; then
      #       echo "No changes detected. Skipping job."
      #       exit 0
      #     else
      #       echo "Changes detected. Pushing changes to gitops repo."
      #       git --no-pager diff
      #       git add .
      #       git commit -m "Update tag version in YAML for ${{ env.APPLICATION_NAME }} to ${{ env.tag-version }} - Commit Hash: ${{ github.sha }}"
      #       git push
      #     fi
