# This github workflow will build the docker image and push it to the container registry
name: Docker-Build-and-Push-to-Docker-Hub
run-name: ${{ github.actor }} is running Docker Build & Push to Docker Hub
on:
  push:
    branches:
      - dev

env:
  APPLICATION_NAME: map-singapore-app
  DOCKERFILE_PATH: dockerimages

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Environment and run Unit Test
        run: |
          echo "Running tests for ${{ env.APPLICATION_NAME }}"
          echo "Unit Test Complete"

      - name: Run Integration Test
        run: |
          echo "Running Integration tests for ${{ env.APPLICATION_NAME }}"
          echo "Integration Test Complete"

  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.DOCKERFILE_PATH }}/${{ env.APPLICATION_NAME }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.APPLICATION_NAME }}:dev-${GITHUB_SHA::8}
          platforms: linux/amd64,linux/arm64

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - tests
  #     - docker-build-and-push
  #   # Clone gitops-repo
  #   # sed -i "s/image:.*/image: yourapp@${{ needs.build-push.outputs.image-digest }}/" clusters/dev/app.yaml
  #   # git commit -m "chore(dev): bump map-singapore-app to dev-${GITHUB_SHA::8}"
  #   # git push origin main  # GitOps repo main branch
