name: DEV CI
run-name: ${{ github.actor }} is running DEV CI
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  APPLICATION_NAME: map-singapore-app
  DOCKERFILE_PATH: dockerimages

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Environment and run Unit Test
        run: |
          echo "Running tests for ${{ env.APPLICATION_NAME }}"
          echo "Unit Test Complete"

      - name: Run Integration Test
        run: |
          echo "Running Integration tests for ${{ env.APPLICATION_NAME }}"
          echo "Integration Test Complete"
