# This github workflow will build the docker image and push it to the container registry
name: UAT CI & CD
run-name: ${{ github.actor }} is running UAT CI & CD
on:
  push:
    branches:
      - main

env:
  REGION: singapore
  ENVIRONMENT: uat
  APPLICATION_NAME: map-singapore-app
  DOCKERFILE_PATH: dockerimages
  GITOPS_REPO: Tsuweiquan/my-argocd-poc-gitops

jobs:
  # Run test on PR and on Merge to dev and main branch
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Environment and run Unit Test
        run: |
          echo "Running tests for ${{ env.APPLICATION_NAME }}"
          echo "Unit Test Complete"

      - name: Run Integration Test
        run: |
          echo "Running Integration tests for ${{ env.APPLICATION_NAME }}"
          echo "Integration Test Complete"

  docker-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      image-digest: ${{ steps.build-and-push.outputs.digest }}
      image-id: ${{ steps.build-and-push.outputs.imageid }}
      tag-version: ${{ steps.generate-tag-version.outputs.tag-version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Image Tag Version
        id: generate-tag-version
        run: |
          VERSION_TXT_FILEPATH="${{ env.DOCKERFILE_PATH }}/${{ env.APPLICATION_NAME }}/version.txt"
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]] || [[ "${{ github.ref }}" == "refs/heads/feature/*" ]]; then
            TAG_VERSION="SNAPSHOT-$(cat $VERSION_TXT_FILEPATH)"
          else
            TAG_VERSION="$(cat $VERSION_TXT_FILEPATH)"
          fi
          echo $TAG_VERSION
          echo "TAG_VERSION=$TAG_VERSION" >> "$GITHUB_ENV"
          echo "tag-version=$TAG_VERSION" >> "$GITHUB_OUTPUT"

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.DOCKERFILE_PATH }}/${{ env.APPLICATION_NAME }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.APPLICATION_NAME }}:${{ env.TAG_VERSION }}
          platforms: linux/amd64,linux/arm64

      - name: Create and Push GitHub Tag
        run: |
          git config --global user.email "github-actions[Deployment Bot]@users.noreply.github.com"
          git config --global user.name "github-actions[Deployment Bot]"
          TAG_NAME="${{ env.TAG_VERSION }}"
          git tag -a $TAG_NAME -m "Automated tag for commit ${{ github.sha }}. Application Version: ${{ env.TAG_VERSION }}"
          git push origin $TAG_NAME

      - name: Create Github Release
        id: create_release
        uses: comnoco/create-release-action@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.TAG_VERSION }}
          release_name: Release ${{env.APPLICATION_NAME}}:${{ env.TAG_VERSION }}
          # body: |
          #   Changes in this Release
          #   - First Change
          #   - Second Change
          # draft: false
          # prerelease: false

  deploy:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    needs:
      - tests
      - docker-build-and-push

    steps:
      - env:
          image-digest: ${{ needs.docker-build-and-push.outputs.image-digest }}
          image-id: ${{ needs.docker-build-and-push.outputs.image-id }}
          tag-version: ${{ needs.docker-build-and-push.outputs.tag-version }}
        run: |
          echo "image-digest=${{ env.image-digest }}" >> $GITHUB_ENV
          echo "image-id=${{ env.image-id }}" >> $GITHUB_ENV
          echo "tag-version=${{ env.tag-version }}" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          repository: ${{ env.GITOPS_REPO }}
          ref: "main"
          token: ${{ secrets.PAT_TOKEN }}
          show-progress: true
          fetch-depth: 0

      - name: Update Tag Version in YAML & Create PR
        uses: fjogeleit/yaml-update-action@v0.16.1
        id: update-yaml-and-create-pr
        with:
          method: Update
          valueFile: "applications-values/${{ env.REGION }}/${{ env.ENVIRONMENT }}/${{ env.APPLICATION_NAME }}/values.yaml"
          propertyPath: "image.tag"
          value: ${{ env.tag-version }}
          repository: ${{ env.GITOPS_REPO }}
          branch: "release/${{ env.APPLICATION_NAME }}-${{ env.tag-version }}"
          targetBranch: "main"
          masterBranchName: "main"
          createPR: true
          title: "Release ${{ env.APPLICATION_NAME }}:${{ env.tag-version }} to ${{ env.ENVIRONMENT }} environment"
          message: "Update Image Version for ${{ env.APPLICATION_NAME }} to ${{ env.tag-version }}"
          token: ${{ secrets.PAT_TOKEN }}
          commitChange: true

      - name: Get PR Details
        id: get-pr-details
        env:
          commit: ${{ steps.update-yaml-and-create-pr.outputs.commit }}
          pull_request: ${{ steps.update-yaml-and-create-pr.outputs.pull_request }}
        run: |
          echo "Git Commit SHA: ${{ env.commit }}"
          echo "Git PR Information: ${{ env.pull_request }}"

      - name: Trigger prod workflow to prepare promotion PR
        run: |
          gh workflow run prod-cd.yml --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
