# This github workflow will build the docker image and push it to the container registry
name: UAT CI
run-name: ${{ github.actor }} is running UAT CI
on:
  pull_request:
    branches:
      - main

env:
  REGION: singapore
  ENVIRONMENT: uat
  APPLICATION_NAME: map-singapore-app
  DOCKERFILE_PATH: dockerimages
  GITOPS_REPO: Tsuweiquan/my-argocd-poc-gitops

jobs:
  # Run test on PR and on Merge to dev and main branch
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Environment and run Unit Test
        run: |
          echo "Running tests for ${{ env.APPLICATION_NAME }}"
          echo "Unit Test Complete"

      - name: Run Integration Test
        run: |
          echo "Running Integration tests for ${{ env.APPLICATION_NAME }}"
          echo "Integration Test Complete"

  docker-build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-digest: ${{ steps.build-and-push.outputs.digest }}
      image-id: ${{ steps.build-and-push.outputs.imageid }}
      tag-version: ${{ steps.generate-tag-version.outputs.tag-version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Image Tag Version
        id: generate-tag-version
        run: |
          VERSION_TXT_FILEPATH="${{ env.DOCKERFILE_PATH }}/${{ env.APPLICATION_NAME }}/version.txt"
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]] || [[ "${{ github.ref }}" == "refs/heads/feature/*" ]]; then
            TAG_VERSION="SNAPSHOT-$(cat $VERSION_TXT_FILEPATH)"
          else
            TAG_VERSION="$(cat $VERSION_TXT_FILEPATH)"
          fi
          echo $TAG_VERSION
          echo "TAG_VERSION=$TAG_VERSION" >> "$GITHUB_ENV"
          echo "tag-version=$TAG_VERSION" >> "$GITHUB_OUTPUT"

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.DOCKERFILE_PATH }}/${{ env.APPLICATION_NAME }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.APPLICATION_NAME }}:${{ env.TAG_VERSION }}
          platforms: linux/amd64,linux/arm64
